--
--
--insert into STATE_EVENT_T  (ID, NAME) values (1, 'PENDING') ON CONFLICT (ID) DO update
--  set ID = excluded.ID,
--      NAME = excluded.NAME;
--insert into STATE_EVENT_T  (ID, NAME) values (2, 'PUBLISHED') ON CONFLICT (ID) DO update
--  set ID = excluded.ID,
--      NAME = excluded.NAME ;
--insert into STATE_EVENT_T  (ID, NAME) values (3, 'CANCELED') ON CONFLICT (ID) DO update
--  set ID = excluded.ID,
--      NAME = excluded.NAME;
--insert into STATE_REQUEST_T  (ID, NAME) values (1, 'PENDING') ON CONFLICT (ID) DO update
--  set ID = excluded.ID,
--      NAME = excluded.NAME;
--insert into STATE_REQUEST_T  (ID, NAME) values (2, 'CONFIRMED') ON CONFLICT (ID) DO update
--  set ID = excluded.ID,
--      NAME = excluded.NAME ;
--insert into STATE_REQUEST_T  (ID, NAME) values (3, 'REJECTED') ON CONFLICT (ID) DO update
--  set ID = excluded.ID,
--      NAME = excluded.NAME ;
