version: '3.1'
services:

  stats-server:
    build: stats/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=daryaserova
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=explore-with-me

  ewm-service:
    build: main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/explore-with-me-main
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - SERVICES_STATSSERVICE_URI=http://stats-server:9090
      - JAVA_OPTS=-Djdk.httpclient.WebClient.log=errors,requests

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=daryaserova
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=explore-with-me-main